### ISSUE TITLE
Can not prettier format .less file in VSCode

### ISSUE THREAD

**Issue by lcysgsg** [umijs/fabric#88]
### Summary

`prettier-plugin-style-order` 依赖 `prettier v1.19.1`, 但是 VSCode prettier 依赖 `prettier ^2`. 不兼容.

经过测试，只要把 `prettier-plugin-style-order` 中的 `prettier` 升级到 `^2` 就能正常运行.

但是，`prettier-plugin-style-order` 的仓库跟npm 版本都对不上... 我觉得它可能不怎么维护了？所以把 issues 提到了这里。

### Github Repository to Reproduce Issue

```less
// @import '~antd/dist/antd.less';  

.bg {
  height: 100vh;
  overflow: hidden;
  background: url(../assets/bg.jpg) no-repeat;
  background-size: cover;
}
// @import './ScienceLayoutTheme.less';
// https://pro.ant.design/docs/style-cn#%E8%A6%86%E7%9B%96%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F
:global {
  .ant-card {
    background: transparent !important;border-width: 1px;
  border-color: rgb(127, 183, 255);
  border-style: solid;
  border-radius: 6px;
  background-color: rgba(127, 183, 255, 0.078);
  box-shadow: inset 0px 0px 16px 4px rgba(127, 183, 255, 0.45);
  }
}
```

### Additional information
 
> Prettier VSCode 6.4.0
> VSCode: 
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

## Prettier Log Output

```
["INFO" - 下午3:39:17] Extension Name: esbenp.prettier-vscode.
["INFO" - 下午3:39:17] Extension Version: 6.4.0.
["INFO" - 下午3:39:20] Formatting c:\lcysgsg\code\github\prettier-plugin-style-order\ScienceLayout.less
["INFO" - 下午3:39:20] Using config file at 'c:\lcysgsg\code\github\prettier-plugin-style-order\prettier.config.js'
["INFO" - 下午3:39:20] Using ignore file (if present) at c:\lcysgsg\code\github\prettier-plugin-style-order\.prettierignore
["INFO" - 下午3:39:20] File Info:
{
  "ignored": false,
  "inferredParser": "less"
}
["INFO" - 下午3:39:20] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 下午3:39:20] Prettier Options:
{
  "filepath": "c:\\lcysgsg\\code\\github\\prettier-plugin-style-order\\ScienceLayout.less",
  "parser": "less",
  "printWidth": 80,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": ["c:\\lcysgsg\\code\\github\\prettier-plugin-style-order"]
}
["ERROR" - 下午3:39:20] Error formatting document.

CssSyntaxError: <css input>:10:1: Unknown word
	at Input.error (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\input.js:128:16)
	at Parser.unknownWord (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\parser.js:561:22)
	at Parser.other (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\parser.js:166:12)
	at Parser.parse (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\parser.js:75:16)
	at parse (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\parse.js:17:12)
	at new LazyResult (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\lazy-result.js:64:16)
	at Processor.<anonymous> (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\processor.js:142:12)
	at Processor.process (c:\Users\lcysgsg\code\Management\node_modules\postcss\lib\processor.js:121:23)
	at module.exports (c:\Users\lcysgsg\code\Management\node_modules\prettier-plugin-style-order\src\config\sorter.js:8:6)
	at Object.preprocess (c:\Users\lcysgsg\code\Management\node_modules\prettier-plugin-style-order\src\index.js:40:18)
	at Object.parse (c:\Users\lcysgsg\code\Management\node_modules\prettier\index.js:13620:21)
	at coreFormat (c:\Users\lcysgsg\code\Management\node_modules\prettier\index.js:14899:14)
	at format (c:\Users\lcysgsg\code\Management\node_modules\prettier\index.js:15131:14)
	at c:\Users\lcysgsg\code\Management\node_modules\prettier\index.js:57542:12
	at Object.format (c:\Users\lcysgsg\code\Management\node_modules\prettier\index.js:57562:12)
	at t.default.<anonymous> (c:\Users\lcysgsg\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:16897)
	at Generator.next (<anonymous>)
	at s (c:\Users\lcysgsg\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:9119)
```
